title: Qin Group Wiki
description: Resources and tools for research in the Qin group.
theme: just-the-docs

url: https://qin-group.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
